---
deployment:
  tasks:
    - export DEPLOYPATH=/home/celestenext/public_html
    - /bin/cp -R wp-content/themes/celeste $DEPLOYPATH/wp-content/themes/
    - /bin/cp -R wp-content/plugins/celeste $DEPLOYPATH/wp-content/plugins/