---
deployment:
  tasks:
    - /bin/cp -R wp-content/themes/celeste /home/celestenext/public_html/wp-content/themes/
    - /bin/cp -R wp-content/plugins/celeste /home/celestenext/public_html/wp-content/plugins/